=== GoppeltM/PPC-Manager/Trunk/PPC Manager/PPC Manager/TournamentPortal.dtd
<?xml encoding="UTF-8"?>
<!--- DTD for the XML-structure used to export players of a tournament and afterwards import the result
  
  Version History
  2011-03-29  wh@datenautomaten.nu  1st Edition
--> 

<!-- Datumsformat: yyyy-MM-dd -->
<!ELEMENT tournament (competition+)>
<!ATTLIST tournament
  name CDATA #REQUIRED
  start-date CDATA #REQUIRED
  end-date CDATA #REQUIRED
  tournament-id CDATA #REQUIRED
>

<!-- Bei der Auslieferung der Spielerliste ist <matches> nicht vorhanden.
Beim Zurückspielen kann es vorhanden sein. 
Wenn es nicht vorhanden ist, werden die Daten der <competition> nicht verändert.

start-date Format : yyyy-MM-dd HH:mm
-->
<!ELEMENT competition (players, matches?)>
<!ATTLIST competition
  age-group CDATA #REQUIRED
  type (Einzel|Doppel|Mixed|Mannschaft) #REQUIRED
  start-date CDATA #REQUIRED
  ttr-from CDATA #IMPLIED
  ttr-to CDATA #IMPLIED
  ttr-remarks CDATA #IMPLIED
>

<!-- Wenn keine <player>-Elemente vorhanden sind, ist noch keine Spielerliste für diese Konkurrenz vorhanden.  -->
<!ELEMENT players (player*)>

<!-- 2e Person ist nur beim Doppelspieler vorhanden 

team-name und team-nr wird dann verwendet zur korrekte Darstellung der Mannschafts-Turniere
-->
<!ELEMENT player (person,person?)>
<!ATTLIST player
  type (single|double) #REQUIRED
  id ID #REQUIRED
  team-name CDATA #IMPLIED
  team-nr CDATA #IMPLIED
>

<!-- Verbindung von firstname, lastname, birthyear, licence-nr ist eindeutig. -->
<!ELEMENT person EMPTY>
<!ATTLIST person
  firstname CDATA #REQUIRED
  lastname CDATA #REQUIRED
  birthyear CDATA #REQUIRED
  internal-nr CDATA #REQUIRED
  licence-nr CDATA #REQUIRED
  sex (0|1|2) #REQUIRED
  club-name CDATA #IMPLIED
  club-nr CDATA #IMPLIED
  club-federation-nickname CDATA #IMPLIED
  ttr CDATA #IMPLIED
  ttr-match-count CDATA #IMPLIED
>

<!-- leere Liste -> vorhandene Spiele werden gelöscht -> Bewerb wird zurückgesetzt.

-->
<!ELEMENT matches (match*)>


<!--  

Sortierung nach Competition, match.nr, match.group.
Gruppierung nach Competition, match.group

IDREF: ID des Spielers muss bei dieser competition.players vorhanden sein.

scheduled Format : yyyy-MM-dd HH:mm

-->
<!ELEMENT match EMPTY>
<!ATTLIST match
  nr CDATA #IMPLIED
  group CDATA #IMPLIED
  scheduled CDATA #IMPLIED
  player-a IDREF #REQUIRED
  player-b IDREF #REQUIRED

  set-a-1 CDATA #REQUIRED
  set-a-2 CDATA #REQUIRED
  set-a-3 CDATA #REQUIRED
  set-a-4 CDATA #REQUIRED
  set-a-5 CDATA #REQUIRED
  set-a-6 CDATA #REQUIRED
  set-a-7 CDATA #REQUIRED
  sets-a (0|1|2|3|4|5|6|7) #REQUIRED
  matches-a (0|1)  #REQUIRED
  games-a CDATA #REQUIRED
  
  set-b-1 CDATA #REQUIRED
  set-b-2 CDATA #REQUIRED
  set-b-3 CDATA #REQUIRED
  set-b-4 CDATA #REQUIRED
  set-b-5 CDATA #REQUIRED
  set-b-6 CDATA #REQUIRED
  set-b-7 CDATA #REQUIRED
  sets-b (0|1|2|3|4|5|6|7) #REQUIRED
  matches-b (0|1) #REQUIRED
  games-b CDATA #REQUIRED
>

=== GoppeltM/PPC-Manager/Trunk/PPC Manager/PPC Manager Tests/Resources/Turnierteilnehmer.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tournament SYSTEM "http://www.datenautomaten.nu/dtd/nuLiga/TournamentPortal.dtd"[]>
<tournament end-date="2012-09-09" start-date="2012-09-08" name="15. Turnier nach Schweizer Art " tournament-id="Fp12HjV93pTyQlVex23%2FfGT919cb58I9">
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Mädchen U 13" type="Einzel">
    <players></players>
  </competition>
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Jungen U 13" type="Einzel">
    <players></players>
  </competition>
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Jungen U 15" type="Einzel">
    <players></players>
  </competition>
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Mädchen U 15" type="Einzel">
    <players></players>
  </competition>
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Mädchen U 18" type="Einzel">
    <players></players>
  </competition>
  <competition start-date="2012-09-08 11:00" ttr-remarks="-" age-group="Jungen U 18" type="Einzel">
    <players>
      <player type="single" id="PLAYER1">
        <person licence-nr="170225" club-federation-nickname="BaTTV" club-name="VfR Rheinsheim" sex="1" ttr-match-count="0" lastname="Akin" ttr="1299" internal-nr="NU1360042" club-nr="128" firstname="Mikail" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER2">
        <person licence-nr="171058" club-federation-nickname="BaTTV" club-name="TTC Langensteinbach e.V. " sex="1" ttr-match-count="0" ttr="1276" lastname="Axtmann" internal-nr="NU1367324" club-nr="428" firstname="Dominik" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER3">
        <person licence-nr="121511" club-federation-nickname="BaTTV" club-name="TTC Edingen-Neckarhausen 1971 e.V." sex="1" ttr-match-count="155" lastname="Bauer" ttr="1276" internal-nr="NU716186" club-nr="803" firstname="Maximilian" birthyear="1995" />
      </player>
      <player type="single" id="PLAYER4">
        <person licence-nr="161858" club-federation-nickname="BaTTV" club-name="FC Dörlesberg e.V. 1946 " sex="0" ttr-match-count="69" lastname="Behringer" ttr="1007" internal-nr="NU1282955" club-nr="1004" firstname="Felicia" birthyear="2003" />
      </player>
      <player type="single" id="PLAYER5">
        <person licence-nr="159495" club-federation-nickname="BaTTV" club-name="TV 1895 e.V. Bad Rappenau" sex="1" ttr-match-count="30" lastname="Belz" ttr="912" internal-nr="NU1256716" club-nr="923" firstname="Maik" birthyear="2000" />
      </player>
      <player type="single" id="PLAYER6">
        <person licence-nr="130612" club-federation-nickname="BaTTV" club-name="TTG 1956 Neckarbischofsheim" sex="0" ttr-match-count="261" lastname="Bohnet" ttr="1197" internal-nr="NU865228" club-nr="920" firstname="Celine" birthyear="1998" />
      </player>
      <player type="single" id="PLAYER7">
        <person licence-nr="143714" club-federation-nickname="BaTTV" club-name="TTG 1956 Neckarbischofsheim" sex="1" ttr-match-count="225" lastname="Bohnet" ttr="1423" internal-nr="NU1084203" club-nr="920" firstname="Nick" birthyear="2002" />
      </player>
      <player type="single" id="PLAYER8">
        <person licence-nr="139772" club-federation-nickname="BaTTV" club-name="TTC Edingen-Neckarhausen 1971 e.V." sex="1" ttr-match-count="134" lastname="Busse" ttr="1209" internal-nr="NU976971" club-nr="803" firstname="Jonathan" birthyear="1995" />
      </player>
      <player type="single" id="PLAYER9">
        <person licence-nr="121471" club-federation-nickname="BaTTV" club-name="TTC Edingen-Neckarhausen 1971 e.V." sex="1" ttr-match-count="148" lastname="Ciupke" ttr="1116" internal-nr="NU716147" club-nr="803" firstname="Marian" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER10">
        <person licence-nr="170222" club-federation-nickname="BaTTV" club-name="VfR Rheinsheim" sex="1" ttr-match-count="0" lastname="Demirkol" ttr="1042" internal-nr="NU1360033" club-nr="128" firstname="Adem" birthyear="1997" />
      </player>
      <player type="single" id="PLAYER11">
        <person licence-nr="166278" club-federation-nickname="BaTTV" club-name="TV 1900 Oberhausen e.V." sex="1" ttr-match-count="28" lastname="Franz" ttr="1044" internal-nr="NU1319810" club-nr="124" firstname="Johannes" birthyear="2002" />
      </player>
      <player type="single" id="PLAYER12">
        <person licence-nr="06051202" club-federation-nickname="TTVWH" club-name="SpVgg Oedheim" sex="0" ttr-match-count="50" lastname="Fränznick" ttr="929" internal-nr="NU1261969" club-nr="06051" firstname="Jasmin" birthyear="2001" />
      </player>
      <player type="single" id="PLAYER13">
        <person licence-nr="06051201" club-federation-nickname="TTVWH" club-name="SpVgg Oedheim" sex="1" ttr-match-count="35" lastname="Fränznick" ttr="771" internal-nr="NU1261968" club-nr="06051" firstname="Simon" birthyear="2004" />
      </player>
      <player type="single" id="PLAYER14">
        <person licence-nr="140573" club-federation-nickname="BaTTV" club-name="DJK St. Hildegard Käfertal Süd" sex="1" ttr-match-count="155" lastname="Glebov" ttr="1297" internal-nr="NU981977" club-nr="503" firstname="Andreas" birthyear="1998" />
      </player>
      <player type="single" id="PLAYER15">
        <person licence-nr="109755" club-federation-nickname="BaTTV" club-name="TTV &quot;Grün-Weiss&quot; Rohrbach" sex="1" ttr-match-count="79" lastname="Heinle" ttr="1209" internal-nr="NU503602" club-nr="925" firstname="Simon" birthyear="1998" />
      </player>
      <player type="single" id="PLAYER16">
        <person licence-nr="152738" club-federation-nickname="BaTTV" club-name="TTV  &quot;Grün-Weiß&quot; Ettlingen e.V." sex="1" ttr-match-count="84" lastname="Held" ttr="1124" internal-nr="NU1169318" club-nr="407" firstname="Julian" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER17">
        <person licence-nr="161583" club-federation-nickname="BaTTV" club-name="TTC Langensteinbach e.V. " sex="1" ttr-match-count="13" lastname="Henning" ttr="809" internal-nr="NU1281063" club-nr="428" firstname="Lukas" birthyear="2000" />
      </player>
      <player type="single" id="PLAYER18">
        <person licence-nr="165223" club-federation-nickname="BaTTV" club-name="TTV  &quot;Grün-Weiß&quot; Ettlingen e.V." sex="0" ttr-match-count="77" lastname="Holfelder" ttr="876" internal-nr="NU587461" club-nr="407" firstname="Sarah" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER19">
        <person licence-nr="24015196" club-federation-nickname="SbTTV" club-name="TTSF Hohberg" sex="1" ttr-match-count="74" lastname="Holub" ttr="1096" internal-nr="NU1255671" club-nr="24015" firstname="Luca" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER20">
        <person licence-nr="171378" club-federation-nickname="BaTTV" club-name="TTC Langensteinbach e.V. " sex="1" ttr-match-count="0" lastname="Höll" ttr="1044" internal-nr="NU1371823" club-nr="428" firstname="Marius" birthyear="2001" />
      </player>
      <player type="single" id="PLAYER21">
        <person licence-nr="146376" club-federation-nickname="BaTTV" club-name="TTV  &quot;Grün-Weiß&quot; Ettlingen e.V." sex="1" ttr-match-count="94" lastname="Knothe" ttr="1182" internal-nr="NU1104478" club-nr="407" firstname="David" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER22">
        <person licence-nr="14036391" club-federation-nickname="TTVWH" club-name="DJK Sportbund Stuttgart" sex="1" ttr-match-count="42" lastname="Kolarski" ttr="1121" internal-nr="NU1256637" club-nr="14036" firstname="Radovan" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER23">
        <person licence-nr="74678" club-federation-nickname="BaTTV" club-name="TTV Mühlhausen 1980 e.V." sex="1" ttr-match-count="35" lastname="Köhler" ttr="1029" internal-nr="NU452525" club-nr="322" firstname="Felix" birthyear="1998" />
      </player>
      <player type="single" id="PLAYER24">
        <person licence-nr="136806" club-federation-nickname="BaTTV" club-name="TTC Dietlingen e.V." sex="1" ttr-match-count="151" lastname="König" ttr="1272" internal-nr="NU491288" club-nr="704" firstname="Ricky" birthyear="1996" />
      </player>
      <player type="single" id="PLAYER25">
        <person licence-nr="105198" club-federation-nickname="BaTTV" club-name="TTC Edingen-Neckarhausen 1971 e.V." sex="1" ttr-match-count="159" lastname="Küsters" ttr="1146" internal-nr="NU463072" club-nr="803" firstname="Patrick" birthyear="1995" />
      </player>
      <player type="single" id="PLAYER26">
        <person licence-nr="170457" club-federation-nickname="BaTTV" club-name="TTV  &quot;Grün-Weiß&quot; Ettlingen e.V." sex="1" ttr-match-count="31" lastname="Lange" ttr="973" internal-nr="NU1264473" club-nr="407" firstname="Philipp" birthyear="1999" />
      </player>
      <player type="single" id="PLAYER27">
        <person licence-nr="157598" club-federation-nickname="BaTTV" club-name="TTV  &quot;Grün-Weiß&quot; Ettlingen e.V." sex="1" ttr-match-count="42" lastname="Lee" ttr="1205" internal-nr="NU1230540" club-nr="407" firstname="Young-Kwang" birthyear="1995" />
      </player>
      <player type="single" id="PLAYER28">
        <person licence-nr="143328" club-federation-nickname="BaTTV" club-name="TTF 1955 Ispringen e.V." sex="1" ttr-match-count="53" lastname="Lippa" ttr="1042" internal-nr="NU1072493" club-nr="713" firstname="André" birthyear="1996" />
      </player>
      <player type="single" id="PLAYER29">
        <person licence-nr="147474" club-federation-nickname="BaTTV" club-name="TTC Langensteinbach e.V. " sex="0" ttr-match-count="105" lastname="Lorenz" ttr="890" internal-nr="NU1120992" club-nr="428" firstname="Kim" birthyear="1998" />
      </player>
      <player type="single" id="PLAYER30">
